# -*- mode: ruby -*-
# vi: set ft=ruby :
#author: TonyFeng

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	(1..3).each do |i|
		config.vm.define "node0#{i}" do |node|
	
		# 设置虚拟机的Box
		node.vm.box = "centos/7"
		# 设置虚拟机的主机名
		node.vm.hostname="node0#{i}"
		# 设置虚拟机本地(即宿主机)使用的IP
		node.vm.network "private_network", ip: "192.168.33.#{i}"

		# 宿主机与虚拟机22端口转发映
		# config.vm.network "forwarded_port", guest: 22, host: "220#{i}"
		node.vm.network "forwarded_port", guest: 22, host: "220#{i}"
		node.vm.network "forwarded_port", guest: 21, host: "212#{i}"
		if i==1
			node.vm.network "forwarded_port", guest: 8080, host: 7000
		end
		# node.vm.network "forwarded_port", guest: 9998, host: 9999, protocol: "tcp", id: "nc"

		# 设置宿主机与虚拟机的共享目录 (默认当前目录会挂载到虚机主用户目录下/home/vagrant)
		#node.vm.synced_folder "~/Desktop/share", "/home/vagrant/share"

		# 拷贝相应的依赖文件
		config.vm.provision "file", source: "../apps/jdk-8u202-linux-x64.tar.gz", destination: "/home/vagrant/apps/jdk-8u202-linux-x64.tar.gz"
		config.vm.provision "file", source: "../sshd_config", destination: "/home/vagrant/sshd_config"
		config.vm.provision "file", source: "../test", destination: "/home/vagrant/test"
		config.vm.provision "file", source: "../yum", destination: "/home/vagrant/yum"
		config.vm.provision "file", source: "scripts/sudoers", destination: "/home/vagrant/scripts"
		config.vm.provision "file", source: "ssh-auto-login", destination: "/home/vagrant/ssh-auto-login"
		
		# VirtaulBox相关配置
		node.vm.provider "virtualbox" do |v|
			# 设置虚拟机的名称
			v.name = "node0#{i}"
			# 设置虚拟机的内存大小  
			v.memory = 1024
			# 设置虚拟机的CPU个数
			v.cpus = 1
		end
		# node.vm.provision "shell", inline: "echo ${i} >> /home/vagrant/apps/zookeeper/data/myid"
		# node.vm.provision "shell", inline: $clusters_script # 使用shell脚本进行软件安装和配置
		# 配置jdk hadoop flink大数据开发环境变量
		node.vm.provision "shell", path: "scripts/cluster-env.sh" 
		# 更换国内yum源
		node.vm.provision "shell", path: "scripts/replace-yum-repo.sh" 
		# 同步集群时间
		node.vm.provision "shell", path: "scripts/sync-time.sh" 
		# adduser usergroup sudoers
		node.vm.provision "shell", path: "scripts/add-user.sh" 
		# add docker alias
		#node.vm.provision "shell", path: "scripts/add-docker-alias.sh"
		# todo:  auto login without password 
		# node.vm.provision "shell", path: "scripts/ssh-group.sh" 

		end
	end
end
